When constructing a Context from a HeaderMap, fill in the env_config field
awslabs/aws-lambda-rust-runtime pull request #248
Opened 2020-08-04 02:50 UTC by khuey

*Description of changes:* Currently this just produces a useless env_config.

By submitting this pull request

- [X] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [X] I confirm that I've made a best effort attempt to update all relevant documentation.

2020-08-04 10:17 UTC, rimutaka commented
Good spotting!

We also missed `pub client_context: Option<ClientContext>` and `pub identity: Option<CognitoIdentity>` in the same `Context ` structure.
They are declared, but are never used. I'll need both of them in a few weeks, so if no one fixes it by then I'll have to :)

2020-08-04 18:44 UTC, khuey commented
Doesn't look like `ClientContext` or `CognitoIdentity` have any existing `from_the_relevant_thing` methods though, so I'd prefer just to merge this as is :)

2020-09-08 18:24 UTC, khuey commented
Ping?

2020-09-12 18:46 UTC, davidbarsky commented
Apologies for the delay, @khuey. This looks good to me, and sorry for missing this!

2020-09-12 18:46 UTC, davidbarsky approved these changes

2020-09-12 18:49 UTC, davidbarsky requested changes

2020-09-12 18:49 UTC, davidbarsky commented on lambda/src/types.rs
> +            env_config: Config::from_env()?,
Actually, I may have spoken too soon. What do you think about populating the `env_config` field _not_ in the `TryFrom<HeaderMap>` impl block but within the execution of the runtime? This would allow this HeaderMap to remain _mostly_ pure (error-handling aside) and make it easier to test and simulate.

2020-09-12 23:44 UTC, khuey commented on lambda/src/types.rs
> +            env_config: Config::from_env()?,
Well the downside would be that every call site would have to do this. Currently there's only one so it's not a big deal. Do you anticipate more being added in the future?

2020-09-12 23:56 UTC, davidbarsky commented on lambda/src/types.rs
> +            env_config: Config::from_env()?,
The only other places where I can imagine this being added is in `lambda_http` and a yet-to-be-implemented mock runtime.

2020-10-08 15:22 UTC, khuey commented on lambda/src/types.rs
> +            env_config: Config::from_env()?,
Comment addressed.

2020-10-10 15:00 UTC, davidbarsky approved these changes
Thanks!

2020-10-27 19:46 UTC, khuey commented
Anybody going to merge this?

2020-10-27 20:40 UTC, davidbarsky approved these changes

2020-10-27 20:41 UTC, merged