Upgrade to tokio 1.0
awslabs/aws-lambda-rust-runtime pull request #276
Opened 2021-01-06 01:51 UTC by coolreader18

*Issue #, if available:*

*Description of changes:*

By submitting this pull request

- [ ] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [ ] I confirm that I've made a best effort attempt to update all relevant documentation.

2021-01-08 17:06 UTC, simnalamburt commented
For the people looking for Tokio 1.0 support of aws-lambda-rust-runtime: Netlify's fork already has Tokio 1.0 support. FYI

###### References
- https://github.com/awslabs/aws-lambda-rust-runtime/issues/274
- https://github.com/netlify/aws-lambda-rust-runtime/pull/8

2021-01-19 22:01 UTC, johansmitsnl commented
@coolreader18 I can confirm that it is working :+1: solved many hours debugging why it was not working with `0.46` of `rusoto`.

Hoping to see this merged soon.

2021-01-25 00:37 UTC, coltonweaver requested changes
Overall this is a great contribution and we are very appreciative for it! Looking forward to hearing back.

2021-01-25 00:37 UTC, coltonweaver commented on lambda/src/simulated.rs
> +        self.buffer.truncate(remaining_buffer_size);
I'm conflicted on how I feel about this change specifically. It seems like quite a bit of extra code to achieve necessarily the same thing, unless I'm totally mistaken.

Just to confirm my understanding - you split the buffer into two slices left and right, check if `bytes_to_read` is less than or equal to the length of the right buffer, at which point you take what you need from the right buffer to place into the `to_buf`. If `bytes_to_read` is greater than the right, then you take what you need from the left and return both all of the right buffer and what you've taken from the left. And then finally you truncate the buffer before returning.

It just seems like a lot of extra code that makes this somewhat difficult to follow. Is it necessary? If so, is there a way we could simplify this or at least comment a bit on the intention here?

2021-01-25 01:38 UTC, coolreader18 commented on lambda/src/simulated.rs
> +        self.buffer.truncate(remaining_buffer_size);
Yeah, so `self.buffer` is a VecDeque, i.e. not contiguous. However, that doesn't mean that you can't get contiguous slices from it, and the repeated `pop_back().unwrap()` seemed inefficient, especially when the equivalent for `tokio::io::ReadBuf` would be repeated `.put_slice(&[i])`. I can definitely add comments to the code, but it's essentially taking `bytes_to_read` bytes from the end of the buffer, than feeding them backwards into the read buf. The truncation is to formally "take" the slice we've read out of the buffer. It's more complicated in code than it might sound since there's 2 slices that make up the VecDeque, but that's all it's doing.

2021-01-25 01:40 UTC, coolreader18 commented on lambda/src/simulated.rs
> +        self.buffer.truncate(remaining_buffer_size);
Though, I think this can be a lot simpler, since it doesn't need to be reversed at all if we append instead of prepend in `BufferState::write()`

2021-01-26 01:25 UTC, TransientError commented on lambda/src/simulated.rs
> +        self.buffer.drain(..bytes_to_read);
Thanks for your PR! We really want to get the new tokio update out as soon as we can. I'm a little skeptical about if this is really necessary though especially since `simulated.rs` is used for testing only. Do you think we can separate this out to a separate issue for more discussion?

2021-01-26 01:41 UTC, coolreader18 commented on lambda/src/simulated.rs
> +        self.buffer.drain(..bytes_to_read);
Alright, I've removed that change from the PR.

2021-01-26 16:25 UTC, coltonweaver approved these changes

2021-01-26 16:26 UTC, coltonweaver commented
To me, everything looks good. I played around with this on my side and things seem to be functioning as expected as well. Going to ask the others to take a look just for posterity, but hopefully we can get this merged in soon.

2021-01-26 16:30 UTC, coltonweaver commented on lambda/src/simulated.rs
> +        self.buffer.truncate(remaining_buffer_size);
Thanks for addressing these. I'll take a look at the PR you split off from this soon.

2021-01-26 16:36 UTC, LucioFranco approved these changes

2021-01-26 16:41 UTC, davidbarsky commented on lambda/src/simulated.rs
> +        self.buffer.truncate(remaining_buffer_size);
Since Tokio now has https://docs.rs/tokio/1.1.0/tokio/io/struct.DuplexStream.html, I think this code can be removed wholesale—I wrote this code initially to mimic this. I think it's largely compatible?

2021-01-26 17:02 UTC, davidbarsky approved these changes
Approved with a few nits.

2021-01-26 17:02 UTC, davidbarsky commented on lambda/src/simulated.rs
>  }
I mentioned this in a comment elsewhere, but I think that SimStream can be replaced with [`tokio::io::Duplex`](https://docs.rs/tokio/1.1.0/tokio/io/struct.DuplexStream.html). This isn't a blocker to merging, however, but it _would_ reduce how much code needs to be in this crate.

(I think some usages in tests would require a `std::sync::Arc`, but I'm not sure.)

2021-01-26 18:50 UTC, coltonweaver commented
@coolreader18 Thoughts on the comments left by @davidbarsky? Don't worry about removing the SimStream in this PR, I'm mainly talking about changing the dependency changes slightly. I think once that's done I'll merge this PR in.

2021-01-26 18:56 UTC, coolreader18 commented on lambda/Cargo.toml
> -tower-service = "0.3"
I feel like it makes sense to use the re-export from hyper - it is part of the public API, and I think it makes it more clear that hyper uses that trait as well, rather than us integrating with something else from the tower stack. I dunno either :shrug:

2021-01-26 19:44 UTC, merged

2021-01-26 19:44 UTC, coltonweaver commented
Alright, we're merged in. Thanks for the PR and addressing the feedback so quickly!