Set env_config value and add Serialize/Deserialize for Context
awslabs/aws-lambda-rust-runtime pull request #308
Opened 2021-03-21 21:03 UTC by rimutaka

Closes #260 

*Description of changes:*

1. Initialize the value for `Context::env_config` which was declared in master many commits ago, but was never set to anything
2. Add `#[derive(Serialize, Deserialize)]` to `Context` and `Config` structs

This change enables proxy-ing lambda requests via transports like AWS SQS for local debugging.
Adding Ser/Deser does not affect the binary size unless those features actually used, so there is no point making it a feature.

See issue #260 for background discussion and https://github.com/rimutaka/lambda-debug-proxy for a proxy example.

By submitting this pull request

- [x] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [x] I confirm that I've made a best effort attempt to update all relevant documentation.

2021-03-26 13:54 UTC, dspatoulas commented
We are having a similar issue using the v0.3.0 version of the runtime in a local or non AWS lambda environment. I can confirm without these changes (or setting the environment variables in docker-compose), when running the `aws-lambda-rust-runtime` in the official AWS Lambda container image (`public.ecr.aws/lambda/provided:al2`) using the examples in the repo causes the runtime to panic. 

We planned to open a similar merge request in the near future, but will hold off until the maintainers have a chance to respond to this MR.

2021-03-27 19:55 UTC, bahildebrand requested changes
Overall this looks good. I think we might want to add some automated tests to prevent a regression like this in the future. I'll open an issue and look into it.

2021-03-27 19:55 UTC, bahildebrand commented on README.md
> +Lambdas can be run and debugged locally using a special [Lambda debug proxy](https://github.com/rimutaka/lambda-debug-proxy), which is a Lambda function that forwards incoming requests to one AWS SQS
This looks like an awesome project! Would you mind mentioning that it's not an Amazon managed project somewhere in this paragraph?

2021-03-27 19:55 UTC, bahildebrand commented on lambda-runtime/Cargo.toml
> +version = "0.3.1"
Can we take the version bump out of this PR? We usually do it as a part of the release process.

2021-03-28 03:27 UTC, rimutaka commented on README.md
> +Lambdas can be run and debugged locally using a special [Lambda debug proxy](https://github.com/rimutaka/lambda-debug-proxy), which is a Lambda function that forwards incoming requests to one AWS SQS
See https://github.com/awslabs/aws-lambda-rust-runtime/pull/308/commits/b7a2be806c0acbbe9e239624ac6e6dae8dc6177b.

2021-03-28 03:27 UTC, rimutaka commented on lambda-runtime/Cargo.toml
> +version = "0.3.1"
Done. See https://github.com/awslabs/aws-lambda-rust-runtime/pull/308/commits/317a362f243f60e4670bc3704135c3bfd1f20131

2021-03-28 14:56 UTC, bahildebrand approved these changes
LGTM

2021-03-28 14:57 UTC, merged