feat: inject user agent in Lambda runtime API calls
awslabs/aws-lambda-rust-runtime pull request #363
Opened 2021-11-11 12:54 UTC by nmoutschen

*Issue #, if available:*

*Description of changes:*

This injects a User-Agent header into the Lambda runtime API calls to track usage of Rust for provided/provided.al2 Lambda runtimes.

By submitting this pull request

- [x] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [x] I confirm that I've made a best effort attempt to update all relevant documentation.

2021-11-11 19:13 UTC, rimutaka commented on lambda-runtime/src/requests.rs
> +            .header("User-Agent", format!("aws-lambda-rust/{}", env!("CARGO_PKG_VERSION")))
`format!()` is 3 times slower than `[].concat()`. See https://github.com/hoodie/concatenation_benchmarks-rs. I've just re-run the benches on the latest nightly and it gave me 23ns vs 79ns on my laptop.

2021-11-12 06:36 UTC, nmoutschen commented on lambda-runtime/src/requests.rs
> +            .header("User-Agent", format!("aws-lambda-rust/{}", env!("CARGO_PKG_VERSION")))
Thanks! I've changed it to `["aws-lambda-rust/", env!("CARGO_PKG_VERSION")].concat()`.

Question from me: since both of these values are known at compile time, wouldn't the compiler already optimize them to prevent concatenation at run time?

2021-11-12 07:17 UTC, SebastianEdwards commented
@nmoutschen anything those of us using custom Rust runtimes (not this crate) can do to signal our usage and support of Rust to AWS?

2021-11-12 07:24 UTC, nmoutschen commented
@SebastianEdwards If you use a similar pattern (<runtime name>/<version>) for the User-Agent, and you let me know what pattern you'll use, we can track it. 😁 I'll just ask that you don't prefix your runtime name with "aws-lambda".

E.g. if you made a runtime called "sebs-awesome-runtime", you can pass a "sebs-awesome-runtime/0.1.0" User-Agent to the Lambda runtime API.

2021-11-12 07:29 UTC, SebastianEdwards commented
> E.g. if you made a runtime called "sebs-awesome-runtime", you can pass a "sebs-awesome-runtime/0.1.0" User-Agent to the Lambda runtime API.

Haha, alright, I guess the user-agent is just going to have to be "sebs-awesome-runtime" then. Will add the header next week

2021-11-13 11:13 UTC, simonvandel requested changes
You can avoid allocations for `User-Agent` by 
defining it once as a const:
```rust
const USER_AGENT: &'static str = concat!("aws-lambda-rust/", env!("CARGO_PKG_VERSION"));
```

See https://godbolt.org/z/8fPdxWKrn for a comparison on the generated ASM.

2021-11-14 21:24 UTC, coltonweaver commented on lambda-runtime/src/requests.rs
> +            .header("User-Agent", format!("aws-lambda-rust/{}", env!("CARGO_PKG_VERSION")))
Hey! I actually ran into this recently in another project. I think it comes down to `concat` being able to call through to an implementation that is specifically optimized for combining the two `&str` inputs. `format!` doesn't have this due to the need for being extremely flexible.

2021-11-14 21:35 UTC, coltonweaver commented
> You can avoid allocations for `User-Agent` by defining it once as a const:
> 
> ```rust
> const USER_AGENT: &'static str = concat!("aws-lambda-rust/", env!("CARGO_PKG_VERSION"));
> ```
> 
> See https://godbolt.org/z/8fPdxWKrn for a comparison on the generated ASM.

Since we're planning on setting this by default on all requests we should 

> You can avoid allocations for `User-Agent` by defining it once as a const:
> 
> ```rust
> const USER_AGENT: &'static str = concat!("aws-lambda-rust/", env!("CARGO_PKG_VERSION"));
> ```
> 
> See https://godbolt.org/z/8fPdxWKrn for a comparison on the generated ASM.

Change overall looks good to me. I agree with @simonvandel that we could probably get away with making this a const using the above. This way we avoid all of the additional allocations on request and response. Thoughts @nmoutschen?

2021-11-14 21:46 UTC, nmoutschen commented
Sounds good! I'll make the changes tomorrow morning.

2021-11-15 15:46 UTC, coltonweaver approved these changes
This looks good. Thanks for addressing the feedback!

2021-11-15 15:46 UTC, merged