Lambda Extensions
awslabs/aws-lambda-rust-runtime pull request #376
Opened 2021-11-29 19:31 UTC by calavera

*Issue #, if available:*

Fixes #261 

*Description of changes:*

This PR introduces two new creates into this project to be able to implement Lambda Extensions in Rust. The work is not completed, and I wanted to share it with you all now that I have functional examples to get people's feedback on the direction I'm taking.

The first create is `lambda-runtime-client`. I've extracted this crate from the current runtime. The idea with this is to be able to reuse clients for different APIs. This brings some guarantees about client behaviors, like having a User-Agent header by default.

The second crate is `lambda-extension`. This crate implements the [Lambda Extensions API,](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html#runtimes-lifecycle-invoke) which is the main point of this PR. I've included two examples in this new crate so I can get feedback about the API exposed to developers that want to create extensions in Rust.

[Basic Example](lambda-extension/examples/basic.rs)
[Example that reports errors to the Extensions API](lambda-extension/examples/error_handling.rs)

There are a few things missing to get this PR in a mergeable state, mostly documentation, but I'll appreciate your input sooner rather than later so I can make these changes better.

By submitting this pull request

- [x] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [ ] I confirm that I've made a best effort attempt to update all relevant documentation.

2021-11-29 19:47 UTC, nmoutschen commented
Thanks a lot for taking the time to create this PR @calavera ! I'll take a look at it tomorrow. 😄

2021-11-29 20:22 UTC, rimutaka commented on lambda-extension/Cargo.toml
> +anyhow = "1.0.48"
We dropped `anyhow` a while ago.

2021-11-29 20:53 UTC, calavera commented on lambda-extension/Cargo.toml
> +anyhow = "1.0.48"
oh yeah, it's not even used. I forgot to remove it. Thanks for pointing that out.

2021-11-30 14:13 UTC, nmoutschen requested changes
Hey @calavera!

Thanks a lot for the time and efforts in creating this PR! Overall it's pretty solid and I'm for the idea of splitting the API client into its separate crate.

In term of potential improvements before merging this, there are three main points for me:

* I'm not too keen on adding a dependency on `async_trait`, as it would diverge from how the `Handler` trait works at the moment.
* I think we should push error handling under the hood as much as possible by catching the `Err`s and sending the right API call on behalf of the developer.
* Right now, `lambda-extension` listens to both INVOKE and SHUTDOWN events. While doing an Ok(()) is not a big deal, I think it would be nice to be able to configure what events to listen to, and then get an enum as payload.

2021-11-30 14:13 UTC, nmoutschen commented on lambda-extension/examples/error_handling.rs
> +        let req = init_error(extension_id, &format!("{}", err), None)?;
Unsure if this is the right way to handle it. Ideally, we should probably abstract errors away from the developers, through the `Err`, and map it manually within the `run` function.

If we get an error after register, we should automatically send a call to `/extension/init/error`, or `/extension/exit/error` if it's after a shutdown call.

2021-11-30 14:13 UTC, nmoutschen commented on lambda-extension/src/lib.rs
> +                    extension.on_invoke(extension_id, event).await?;
Continuing on the question of error handling, we should probably send a call back to the Extension API at this stage, and then exit.

Reference from the [Lambda documentation](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html#runtimes-extensions-init-error):

> Call it when the extension fails to initialize after it has registered. After Lambda receives the error, no further API calls succeed. The extension should exit after it receives the response from Lambda.

2021-11-30 17:16 UTC, calavera commented on Cargo.toml
> +    "lambda-runtime-client",
I forgot about that. Do you have a name suggestion?

2021-11-30 17:17 UTC, calavera commented on lambda-extension/src/requests.rs
> +        "events": ["INVOKE", "SHUTDOWN"]
let me think how that could look like

2021-12-01 00:39 UTC, davidbarsky commented on Cargo.toml
> +    "lambda-runtime-client",
i would probably resurrect that crate name and use it for this. happy to transfer it over, need be.

2021-12-01 09:00 UTC, nmoutschen commented on Cargo.toml
> +    "lambda-runtime-client",
Yep, I think we could just keep that one there.

2021-12-01 18:42 UTC, calavera commented on Cargo.toml
> +    "lambda-runtime-client",
I've renamed the crate `lambda-runtime-api-client` to avoid confusion. I've also updated the version to keep it in sync with the `lambda-runtime` crate.

2021-12-02 23:56 UTC, calavera commented
@nmoutschen I've updated this PR to address your comments. Can you take a look at the examples now and let me know what you think?

2021-12-03 14:09 UTC, nmoutschen requested changes
Thanks a lot for the update @calavera!

I really like the changes you made! The main change I think would help here before we merge this is on the `Extension` trait signature, by making self mutable to be in line with recent changes in this repository (but not published yet).

I also have some other small remarks/nitpicks, but up to you to decide if you agree with me or not.

2021-12-03 14:09 UTC, nmoutschen commented on lambda-extension/src/lib.rs
> +    fn call(&self, extension_id: ExtensionId, event: NextEvent) -> Self::Fut;
1. I think it would be nice to have `&mut self` here to match more closely the current implementation in the repository (but not yet published). See [this PR](https://github.com/awslabs/aws-lambda-rust-runtime/pull/356) for reference.
2. __NITPICK__: Another remark, but more of a nitpick from me: is there a good use-case to expose the extension ID, or could we keep that internal to the crate?
3. __NITPICK__: Would it be also better to swap the order of arguments here since `event` would be the most used one?

2021-12-03 14:09 UTC, nmoutschen commented on lambda-extension/examples/basic.rs
> +    let func = extension_fn(my_extension);
Love the high-level experience here. 😄

2021-12-03 14:09 UTC, nmoutschen commented on lambda-extension/examples/custom_events.rs
> +async fn main() -> Result<(), Error> {
__OPEN QUESTION__: should we also have an example with a struct that implements the `Extension` trait? E.g. caching/storing data.

2021-12-03 16:57 UTC, calavera commented on lambda-extension/examples/custom_events.rs
> +async fn main() -> Result<(), Error> {
good idea, I'll add one

2021-12-03 17:13 UTC, calavera commented on lambda-extension/src/lib.rs
> +    fn call(&self, extension_id: ExtensionId, event: NextEvent) -> Self::Fut;
you might be right. The extension id is there because the error notifications where send from the user code before. I'll remove it, I rather keep the api simple, and expand it later if necessary.

2021-12-03 20:28 UTC, nmoutschen approved these changes
LGTM from an implementation POV!

2021-12-03 20:28 UTC, nmoutschen commented on lambda-extension/examples/custom_trait_implementation.rs
> +struct MyExtension {}
Should we showcase a trait implementation with some data in the struct?

Could be something as simple as storing all the events coming in and flushing them on shutdown for example.

2021-12-04 01:42 UTC, calavera commented
@nmoutschen I've added documentation where it was necessary and opened the PR for review. Thanks a lot for your feedback.

2021-12-04 23:03 UTC, calavera commented
I still have to update the README with information about this new crate.

2021-12-07 00:14 UTC, calavera commented
@nmoutschen I was not sure where to add information to the main readme, so I opted for creating two specific readmes inside the new crate directories. Let me know what you think.

2021-12-07 08:26 UTC, nmoutschen approved these changes
LGTM! Just 2 small details on libc for various OS versions, and on how users probably won't use the runtime client directly.

2021-12-07 08:26 UTC, nmoutschen commented on lambda-extension/README.md
> +Lambda extensions can be added to your functions either using [Lambda layers](https://docs.aws.amazon.com/lambda/latest/dg/using-extensions.html#using-extensions-config), or adding them to [container
__Nit__: the version of glibc on Amazon Linux 1 runtimes is too old. For AL1, we need to use musl instead of glibc. If someone wants to develop an extension that will run irregardless of OS version, they could use musl.

2021-12-07 08:26 UTC, nmoutschen commented on lambda-runtime-api-client/README.md
> +**`lambda-runtime-api-client`** is a library to interact with the AWS Lambda Runtime API.
__Nit__: I'd add something about how most people probably don't need to use this library directly, and should look at `lambda_runtime` or `lambda_extension` instead.

2021-12-07 18:17 UTC, calavera commented
@nmoutschen I dedided to remove the paragraph about targets explicitly. I think it was confusing and hard to explain. I'd expect that people that want to write extensions are already familiar with functions, and how the runtime works. It's still worth mentioning that the target must match the architecture that functions run on.

2021-12-10 16:33 UTC, calavera commented
@nmoutschen what are the next steps to get this PR merged?

2021-12-10 16:48 UTC, nmoutschen commented
Hey @calavera !

Not much on your side. I wanted to run a complete test by building an extension and running on Lambda before merging this just to make sure. I'm on sick leave at the moment, but I should be able to do it next week.

2021-12-10 17:04 UTC, calavera commented
> Not much on your side. I wanted to run a complete test by building an extension and running on Lambda before merging this just to make sure. I'm on sick leave at the moment, but I should be able to do it next week.

Thanks for letting me know, I wasn't sure if there was anything missing. Take care

2021-12-10 21:06 UTC, nmoutschen commented on lambda-extension/src/lib.rs
> +                args[0].clone()
After doing some tests on Lambda, this causes an issue with the Lambda Extensions API. Because this value contains slashes (e.g. `/opt/extension/my-extension`), the Lambda Extension API will fail to process it correctly, and assumes that this is an internal extension.

Because of this, it will fail to register the extension if it contains/starts with (not sure which one) a slash.

However, taking the last part of the path works. E.g. instead of `/opt/extension/my-extension`, `my-extension` works.

2021-12-10 21:09 UTC, nmoutschen commented
Hey @calavera ! I just found a bug when running a sample Lambda function with a layer, but otherwise everything else works when I changed the full extension path for its basename.

2021-12-11 02:32 UTC, calavera commented on lambda-extension/src/lib.rs
> +                args[0].clone()
good catch! I've updated this code to cleanup the executable name.

2021-12-11 02:33 UTC, calavera commented
@nmoutschen I pushed a new commit that should fixed that problem 🙌

2021-12-11 10:31 UTC, merged

2021-12-11 10:32 UTC, nmoutschen commented
All good now! Merged the PR! Thank again for your contribution here! 🙌