fix: add client context and icognito identity to runtime context
awslabs/aws-lambda-rust-runtime pull request #382
Opened 2021-12-16 18:13 UTC by diceride

*Issue #, if available:*

*Description of changes:*

Fixes an issue where the client context `lambda-runtime-client-context` and the cognito identity `lambda-runtime-cognito-identity` were not deserialized from the incoming request headers.

By submitting this pull request

- [x] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [x] I confirm that I've made a best effort attempt to update all relevant documentation.

2021-12-17 09:26 UTC, diceride commented
The CI clippy warning is unrelated to the changes

2021-12-17 17:08 UTC, diceride commented
Rebased from master a7e17ee

2021-12-18 18:28 UTC, diceride commented
The CI clippy warning is unrelated to the changes. 

@nmoutschen I guess https://github.com/awslabs/aws-lambda-rust-runtime/pull/383 will resolve the warnings?

2021-12-24 16:16 UTC, bahildebrand requested changes
Just to make sure I understand the issue. This was previously panicking if the headers were not present correct? So the addition of these `Option`s allows the deserialization to succeed if they are not present?

Also can you fix any clippy issues?

2021-12-24 16:16 UTC, bahildebrand commented on lambda-runtime/src/types.rs
> +        let client_context: Option<ClientContext> = if let Some(value) = headers.get("lambda-runtime-client-context") {
I think we can replace both of these ifs with [Option::and](https://doc.rust-lang.org/std/option/enum.Option.html#method.and).

2021-12-24 16:18 UTC, bahildebrand commented on lambda-runtime/src/types.rs
> +        let client_context: Option<ClientContext> = if let Some(value) = headers.get("lambda-runtime-client-context") {
Actually should probably be [Option::and_then](https://doc.rust-lang.org/std/option/enum.Option.html#method.and_then)

2021-12-24 17:48 UTC, calavera commented on lambda-runtime/src/types.rs
> +    pub custom: Option<HashMap<String, String>>,
I would recommend to deserialize `custom` and `environment` with their default representation, instead of wrapping them with an option. This is a personal preference but it makes the code easier to manage if you can assume that they always exist. You can do that by adding `#[serde(default)]` above those two fields.

2021-12-24 18:48 UTC, bahildebrand commented on lambda-runtime/src/types.rs
> +    pub custom: Option<HashMap<String, String>>,
I think I'm in agreement that this is the better route here. Using `Option`s here will just result in a lot of extra code for upstream users, and if we can avoid that it would be preferable.

2021-12-24 18:49 UTC, bahildebrand commented on lambda-runtime/src/types.rs
> +        let client_context: Option<ClientContext> = if let Some(value) = headers.get("lambda-runtime-client-context") {
Not necessary if we go with @calavera suggestion. See his comment below.

2021-12-24 19:10 UTC, davidbarsky commented
This isn't really my project to maintain anymore, but as the person who made this decision a few years ago, I think it'd be helpful if I provided a bit of context. At the time—and I believe this is still the case—the client context and Cognito Identity were only filled by the AWS Mobile SDKs that _directly_ invoked Lambda functions. This pattern was discouraged in favor of delegating authentication/authorization to API Gateway, and the thinking was that anyone who'd be using this new runtime will _probably_ not be using those older SDKs.

However, I don't know if this guidance has changed and someone a bit closer to those decisions should weigh in.

2021-12-25 00:54 UTC, calavera commented on lambda-runtime/src/types.rs
> +    pub custom: Option<HashMap<String, String>>,
this is also a breaking change without much reasoning behind it.

2021-12-26 12:29 UTC, diceride commented on lambda-runtime/src/types.rs
> +    pub custom: Option<HashMap<String, String>>,
Oh yes, I like it, it's a very elegant solution.

2021-12-26 12:34 UTC, diceride commented on lambda-runtime/src/types.rs
> +        let client_context: Option<ClientContext> = if let Some(value) = headers.get("lambda-runtime-client-context") {
Initially, I took the Node.js implementation as a reference, where `custom` and `environment` can be of type `undefined`.

2021-12-26 12:36 UTC, diceride commented on lambda-runtime/src/types.rs
> +        let client_context: Option<ClientContext> = if let Some(value) = headers.get("lambda-runtime-client-context") {
I took the Node.js implementation of the AWS Lambda runtime as a reference, where `custom` and `environment` can be of type `undefined`.

Example

https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/blob/e5d62346eb08f1723348197df70d4f55f9c2ebcf/src/Runtime/InvokeContext.ts#L114

and

https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/blob/e5d62346eb08f1723348197df70d4f55f9c2ebcf/src/Runtime/InvokeContext.ts#L159

2021-12-26 12:58 UTC, diceride commented
@davidbarsky Alright, I understand now. Thank you. We use the `custom` property of the client context to transfer metadata to the client. We don't use the Mobile SDKs. The client context seemed to be universal in nature for us, so we were like .. "Hey! There is something that we can use to solve our problem". I noticed that it works in the Node.js client and the .NET client, but not in the Rust client.

https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/blob/e5d62346eb08f1723348197df70d4f55f9c2ebcf/src/Runtime/InvokeContext.ts#L114-L121

https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.RuntimeSupport/Client/RuntimeApiHeaders.cs#L33-L34

2021-12-26 13:18 UTC, diceride commented
@davidbarsky Alright, I understand now. Thank you. We use the `custom` property of the client context to transfer metadata to the client. We don't use the Mobile SDKs. The client context seemed to be universal in nature for us, so we were like .. "Hey, there is something that we can use to solve our problem". 

@bahildebrand 
> This was previously panicking if the headers were not present correct? So the addition of these Options allows the deserialization to succeed if they are not present?
Yes, I noticed that it works in the Node.js client and the .NET client, but not in the Rust client.

https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/blob/e5d62346eb08f1723348197df70d4f55f9c2ebcf/src/Runtime/InvokeContext.ts#L114-L121

https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.RuntimeSupport/Client/RuntimeApiHeaders.cs#L33-L34

2021-12-26 13:19 UTC, diceride commented
@davidbarsky Alright, I understand now. Thank you. We use the `custom` property of the client context to transfer metadata to the client. We don't use the Mobile SDKs. The client context seemed to be universal in nature for us, so we were like .. "Hey, there is something that we can use to solve our problem". 

@bahildebrand 
> This was previously panicking if the headers were not present correct? So the addition of these Options allows the deserialization to succeed if they are not present?

Yes, I noticed that it works in the Node.js client and the .NET client, but not in the Rust client.

https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/blob/e5d62346eb08f1723348197df70d4f55f9c2ebcf/src/Runtime/InvokeContext.ts#L114-L121

https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.RuntimeSupport/Client/RuntimeApiHeaders.cs#L33-L34

2021-12-26 13:20 UTC, diceride commented
@davidbarsky We use the `custom` property of the client context to transfer metadata to the client. We don't use the Mobile SDKs. The client context seemed to be universal in nature for us, so we were like .. "Hey, there is something that we can use to solve our problem". 

@bahildebrand 
> This was previously panicking if the headers were not present correct? So the addition of these Options allows the deserialization to succeed if they are not present?

Yes, I noticed that it works in the Node.js client and the .NET client, but not in the Rust client.

https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/blob/e5d62346eb08f1723348197df70d4f55f9c2ebcf/src/Runtime/InvokeContext.ts#L114-L121

https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.RuntimeSupport/Client/RuntimeApiHeaders.cs#L33-L34

2021-12-27 17:58 UTC, calavera commented on lambda-runtime/src/types.rs
> +    pub client: Option<ClientApplication>,
I wonder if this should also implement default, instead of wrapping it with an option. My main concern is that this is another breaking change for people that might currently be using this `ClientContext`. The `ClientApplication` struct looks easy enough to derive `Defaut`. What do you think @diceride ?

2021-12-27 18:28 UTC, diceride commented on lambda-runtime/src/types.rs
> +    pub client: Option<ClientApplication>,
Well, using `Optional` seemed to be more sound to me. `ClientContext` never worked before (it was never deserialized). So I don't see the _breaking_ (breaking like in "it breaks 50% of user code") change. If you do not use the Mobile SDK (which is not recommended by AWS as @davidbarsky mentioned), the client `context lambda-runtime-client-context` and the cognito `identity lambda-runtime-cognito-identity` headers will never be set. So we can save some bytes by using `None` instead of `Default`. I mean, we are talking about peanuts. Originally, I looked at the Node.js client, where it can be `undefined` and in the .NET client it can be `null`. I'm not sure about other client implementations? I have no strong feelings here, let me know what you think. I can change it either way. Just wanted to point out some arguments. I already wrote too much, this comment is way too long.

2021-12-27 18:36 UTC, diceride commented on lambda-runtime/src/types.rs
> +    pub client: Option<ClientApplication>,
I made it `Default` instead of `Optional` as suggested.

2021-12-27 20:06 UTC, calavera approved these changes
thanks for indulging me with my very own personal opinions @diceride. I really like how clean this looks like now 🙌

2021-12-27 20:27 UTC, bahildebrand approved these changes
LGTM. Waiting on all checks to pass and then I'll merge.

2021-12-28 04:07 UTC, merged