Feature flags for lambda_http
awslabs/aws-lambda-rust-runtime pull request #497
Opened 2022-07-02 19:28 UTC by calavera

Add feature flags to lambda_http so consumer can decide which service their events come from. This makes compilation much faster when you don't put the same Lambda function behind multiple services.

I've tested these changes in a simple function behind APIGW, and compilation time for a pre-compiled function drops from 18 seconds to 5 seconds.

Signed-off-by: David Calavera <david.calavera@gmail.com>

*Issue #, if available:*

Fixes #481 

By submitting this pull request

- [x] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [x] I confirm that I've made a best effort attempt to update all relevant documentation.

2022-07-04 14:57 UTC, david-perez approved these changes
Implementation looks good. Minor comments about wording in the readme.

2022-07-04 14:57 UTC, david-perez commented on README.md
> +`lambda_http` is a wrapper for HTTP events coming from two different services, Amazon Load Balancer (ALB), and AWS Api Gateway (APIGW). AWS Api Gateway can also send events from three different endpo
```suggestion
`lambda_http` is a wrapper for HTTP events coming from two different services, Amazon Load Balancer (ALB), and Amazon API Gateway (APIGW). Amazon API Gateway can also send events from three different endpoints, Proxy V1, Proxy V2, and WebSockets. `lambda_http` transforms events from all these sources into native `http::Request` objects, so you can incorporate Rust HTTP semantics into your Lambda functions.
```

The official name is "Amazon API Gateway".

2022-07-04 14:57 UTC, david-perez commented on README.md
> +By default, `lambda_http` compiles your function to support any of those services, this increases the compile time of your function because we have to generate code for all the sources. In reality, y
```suggestion
By default, `lambda_http` compiles your function to support any of those services. This increases the compile time of your function because we have to generate code for all the sources. In reality, you'll usually put a Lambda function only behind one of those sources. You can choose which source to generate code for with feature flags.
```

2022-07-04 14:57 UTC, david-perez commented on README.md
> +- `alb`: for events coming from Amazon Load Balancer.
ELB Application Load Balancer?

It'd be nice if we added links to each product.

2022-07-04 14:57 UTC, david-perez commented on README.md
> +If you only want to support one of these sources, you can disable the default features, and enable only the source that you care about in your package's Cargo.toml file. Substitute the dependency lin
```suggestion
If you only want to support one of these sources, you can disable the default features, and enable only the source that you care about in your package's `Cargo.toml` file. Substitute the dependency line for `lambda_http` for the snippet below, changing the feature that you want to enable:
```

2022-07-04 14:57 UTC, david-perez commented on README.md
> +This will make your function to compile much faster.
```suggestion
This will make your function compile much faster.
```

2022-07-05 03:24 UTC, bnusunny requested changes

2022-07-05 03:24 UTC, bnusunny commented on README.md
> +`lambda_http` is a wrapper for HTTP events coming from two different services, Amazon Load Balancer (ALB), and Amazon Api Gateway (APIGW). Amazon Api Gateway can also send events from three different
`lambda_http` actually supports three sources: ALB, APIGW, and the new [Lambda Function URLs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-urls.html). Lambda Function URLs use the same event format as APIGW HTTP API [payload format version 2.0](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format). So it works out of box.

2022-07-05 14:47 UTC, bnusunny requested changes

2022-07-05 14:47 UTC, bnusunny commented on README.md
> +`lambda_http` is a wrapper for HTTP events coming from three different services, Amazon Load Balancer (ALB), Amazon Api Gateway (APIGW), and AWS Lambda Function URLs. Amazon Api Gateway can also send
minor one: `REST APis` -> `REST APIs`

2022-07-05 23:50 UTC, bnusunny approved these changes

2022-07-06 00:49 UTC, merged